%VULKAN_SDK%\Bin\glslc.exe Shader.vert -o Shader.vert.spv
%VULKAN_SDK%\Bin\glslc.exe Shader.frag -o Shader.frag.spv
%VULKAN_SDK%\Bin\glslc.exe VertexBuffer.vert -o VertexBuffer.vert.spv
%VULKAN_SDK%\Bin\glslc.exe VertexBuffer.frag -o VertexBuffer.frag.spv
%VULKAN_SDK%\Bin\glslc.exe UniformBuffer.vert -o UniformBuffer.vert.spv
%VULKAN_SDK%\Bin\glslc.exe UniformBuffer.frag -o UniformBuffer.frag.spv
%VULKAN_SDK%\Bin\glslc.exe Texture.vert -o Texture.vert.spv
%VULKAN_SDK%\Bin\glslc.exe Texture.frag -o Texture.frag.spv
%VULKAN_SDK%\Bin\glslc.exe DepthBuffer.vert -o DepthBuffer.vert.spv
%VULKAN_SDK%\Bin\glslc.exe DepthBuffer.frag -o DepthBuffer.frag.spv
%VULKAN_SDK%\Bin\glslc.exe Model.vert -o Model.vert.spv
%VULKAN_SDK%\Bin\glslc.exe Model.frag -o Model.frag.spv